site_name: 计算环境使用说明
site_url: http://10.40.13.225/
repo_url: https://github.com/Alexhaoge/STAT0024-Deploy-Manual

nav:
  - '概述': 'index.md'
  - '分布式存储与计算':
    - 'JupyterHub': 'dsc/jupyter.md'
    - 'Anaconda': 'dsc/conda.md'
    - 'PySpark': 'dsc/pyspark.md'
    - 'Scala': 'dsc/scala.md'
  - '数据库':
    - 'MySQL学生使用说明': 'mysql.md'
  - '管理手册':
    - 'JupyterHub': 'admin/jupyter.md'
    - 'Spark/Hadoop': 'admin/spark_hadoop.md'
    - 'Rstudio': 'admin/rstudio.md'
    - 'MySQL': 'admin/mysql.md'
    - 'ssh&Linux常用操作': 'admin/sshlinux.md'
    - '文件路径记录': 'admin/fs.md'
  - '归档':
    - '归档说明': 'archive/archive.md'
    - 'HDFS': 'archive/hdfs.md'
    - '杂项': 'archive/misc.md'
  - '关于': 'about.md'
# - ['about/admin.md', '关于', '管理员说明']
# - ['about/license.md', '关于', 'License']

theme:
  name: readthedocs

plugins:
  - macros

extra:
    site_ip: 10.40.13.225